# PARAMETERS FOR GADEN PREPROCESSING NODE #
# ======================================== #
gaden_preprocessing:
  ros__parameters:
    # Cell size
    cell_size: 0.1

    # CAD models of the enviroment (.stl)
    models: $(var models)

    # CAD model of the outlets (.stl)
    outlets_models: $(var outlets_models)
    
    # 3D Location of a point in free-space
    empty_point_x: 2.8      ### (m)
    empty_point_y: 6.1      ### (m)
    empty_point_z: 1.0      ### (m)

    floor_height: 0.1
    
    # Wind Data (the node will append _i.csv to the name that is specified here)
    uniformWind: false
    wind_files: "$(var pkg_dir)/scenarios/$(var scenario)/wind_simulations/$(var wind_sim_path)"
    
    # Where to write the output files
    output_path: "$(var pkg_dir)/scenarios/$(var scenario)"